_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
device:
    value: cuda
epochs:
    value: 500
lr:
    value: 0.005
n_hidden_layer1:
    value: 32
n_hidden_layer2:
    value: 64
n_hidden_layer3:
    value: 32
print_every:
    value: 10
train_batch_size:
    value: 4096
wandb_log:
    value: false
